### ISSUE TITLE
Failed to create config file on the first run

### ISSUE THREAD

**Issue by Zverik** [hvdwolf/pyExifToolGUI#12]
It seems the program doesn't check for `~/.pyexiftoolgui` existence. After I make it, it runs fine.

**Comment by hvdwolf** [comment]
It should definitely check for it, but I will check that.

Harry

2015-05-17 12:29 GMT+02:00 Ilya Zverev <notifications@github.com>:

**Comment by Zverik** [comment]
Nope
https://github.com/hvdwolf/pyExifToolGUI/blob/master/scripts/petgfilehandling.py#L43

**Comment by maysara** [comment]
Same issue here, ubuntu linux 14.04, created the directory manually and it worked afterwards

**Comment by hvdwolf** [comment]
I patched it in the repo, but I did not release a new build yet.

**Comment by jedie** [comment]
I used current git clone 6e9cb9648226a4635534b49ca12d44468b5b8779 and the bug still exists:
```
reading from /home/jens/.pyexiftoolgui/config.xml
Traceback (most recent call last):
  File "/home/jens/workspace/pyExifToolGUI/scripts/pyexiftoolgui.py", line 683, in <module>
    frame = MainWindow()
  File "/home/jens/workspace/pyExifToolGUI/scripts/pyexiftoolgui.py", line 183, in __init__
    petgfilehandling.read_xml_config(self)
  File "/home/jens/workspace/pyExifToolGUI/scripts/petgfilehandling.py", line 73, in read_xml_config
    write_default_config()
  File "/home/jens/workspace/pyExifToolGUI/scripts/petgfilehandling.py", line 44, in write_default_config
    config_file = open(os.path.join(userpath, '.pyexiftoolgui', 'config.xml'), "w")
IOError: [Errno 2] Datei oder Verzeichnis nicht gefunden: '/home/jens/.pyexiftoolgui/config.xml'
```

I crreated https://github.com/hvdwolf/pyExifToolGUI/pull/24 for this ;)
