### ISSUE TITLE
pyexiftoolgui not working

### ISSUE THREAD

**Issue by tenmangu81** [hvdwolf/pyExifToolGUI#32]
Hi,

I have downloaded the latest version of pyexiftoolgui, I can load images, but nothing is displayed in the window, whatever I click (all, exif, IPTC,...). The path to exiftool has been specified in the preferences.
Phil Harvey's exiftool works quite well, Exif Editor works quite well, but not pyexiftoolgui !!
Do you have any idea ?
Thanks,
Robert

**Comment by ww7** [comment]
Same here

**Comment by ThatIsAPseudo** [comment]
same here

**Comment by hvdwolf** [comment]
I must admit that I haven't worked on this for years. I assume it is "some" incompatibility with newer OSes.
Are you on win10, on MacOS/x or on Linux?

**Comment by ThatIsAPseudo** [comment]
I'm on macOS Mojave, in fact I noticed that pyexiftoolgui does work with some image imported from a smartphone, but not with jpeg that were previously RAW (.RW2) images (converted in jpeg with Photoshop)

**Comment by michaelherger** [comment]
@darkdragon-001's assumption might be correct. Here's what I get when running pyexiftoolgui from the command line on macOS 10.14.5:

```
2019-06-26 19:36:14.080 pyexiftoolgui[83406:7410363] warning: <NSRemoteView: 0x112e2ad30> determined it was necessary to configure <NSOpenPanel: 0x12092c930> to support remote view vibrancy
2019-06-26 19:36:20.809 pyexiftoolgui[83406:7410363] warning: <NSRemoteView: 0x112e2ad30> determined it was necessary to configure <NSOpenPanel: 0x12092c930> to support remote view vibrancy
2019-06-26 19:36:22.151 pyexiftoolgui[83406:7410363] warning: <NSRemoteView: 0x112e660f0> determined it was necessary to configure <NSOpenPanel: 0x12092c930> to support remote view vibrancy
Traceback (most recent call last):
  File "<string>", line 469, in imageinfo
  File "/Users/Shared/development/python_related/pyside/pyExifToolGUI-0.5/MacOSX/build/pyi.darwin/pyexiftoolgui/out00-PYZ.pyz/petgfunctions", line 516, in imageinfo
  File "/Users/Shared/development/python_related/pyside/pyExifToolGUI-0.5/MacOSX/build/pyi.darwin/pyexiftoolgui/out00-PYZ.pyz/shlex", line 275, in split
  File "/Users/Shared/development/python_related/pyside/pyExifToolGUI-0.5/MacOSX/build/pyi.darwin/pyexiftoolgui/out00-PYZ.pyz/shlex", line 25, in __init__
UnicodeEncodeError: 'ascii' codec can't encode character u'\u0308' in position 72: ordinal not in range(128)
```

Is there any way to fix/work around this?

**Comment by ltf3** [comment]
I'm on Mac Mojave and the GUI tool often won't launch. Sometimes a restart is needed. Once running its seems fine though.

It's such a useful tool though... any hope of an update or replacement? Maybe a real app for sale?

**Comment by hvdwolf** [comment]
It gets more and more difficult to support pyexiftoolgui due to the used pyside libraries, due to the changed licenses but also due to changes in MacOS. Since a couple of years I do not have a Mac anymore.

I'm currently builing on java, which comes with builtin libraries for the graphical screens, and which is so much easier to port to multiple OSes.
I started jexiftoolgui some 7 months back, but haven't done anything in the last 5 months due to "family reasons", but I will finish version 1.0 hopefully somewhere in the Christmas holidays. I'm at 90% or so, so it should not take too much time to finish. It should do exactly the same as pyexiftoolgui

jexiftoolgui: https://github.com/hvdwolf/jExifToolGUI
